### ISSUE TITLE
请问 YLTableViewSection 里的 beforeSelectRowAtIndexPath 和 afterSelectRowAtIndexPath 这两个方法 的作用是什么呢

### ISSUE THREAD

**Issue by TierZ** [ypli-chn/YLTableView#1]
- (BOOL)beforeSelectRowAtIndexPath:(NSIndexPath *)indexPath {  
    return YES;  
}  
  
- (void)afterSelectRowAtIndexPath:(NSIndexPath *)indexPath {  
      
}

**Comment by ypli-chn** [comment]
用于拆分Cell的响应事件用的，原本didSelect事件是在UITableView的delegate来处理的，而delegate只能有一个，一般都是对应的VC，这里相当于把这两个事件转由各个组件各自处理。

**Comment by ypli-chn** [comment]
> * (BOOL)beforeSelectRowAtIndexPath:(NSIndexPath *)indexPath {
>   return YES;
>   }
> * (void)afterSelectRowAtIndexPath:(NSIndexPath *)indexPath {
> 
> }

用于拆分Cell的响应事件用的，原本didSelect事件是在UITableView的delegate来处理的，而delegate只能有一个，一般都是对应的VC，这里相当于把这两个事件转由各个组件各自处理。
